version: '3.1'

services:
    node:
        build:
            context: ./../../
            dockerfile: ./deployment/local/Dockerfile
        container_name: node_${COMPOSE_PROJECT_NAME}
        volumes:
            - ./../../:/app
            - /app/node_modules
        ports:
            - 8000:8000
            - 8080:8080
        networks:
            - net
networks:
    net:
        driver: bridge